import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import ColombiaMap from "../components/colombiaMap";
import TextBack from "../components/textBack";
import FirstText from "../components/firstText";
import ListaNomi from "../components/listaNomi";
import FirstBird from "../components/firstBird";
import MiddleBird from "../components/middleBird";
import ThirdBird from "../components/thirdBird";
import Edera from "../components/edera";
import Header from "../components/header";
import { FormAlert } from "../components/form";
import Lastbird from "../components/lastbird";
export default function Home() {

  const [data, setData] = React.useState(null)

  const getData = () => {
    fetch('./data/dati.json'
      , {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        }
      }
    )
      .then(function (response) {
        return response.json()
      })
      .then(function (myJson) {

        setData(myJson)
      });
  }

  React.useEffect(() => {
    getData()
   
  window.onbeforeunload = function () {
      window.scrollTo(0, 0);
    }

  }, [])


  return (
    <div className='test'>
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/ArchivoBlack-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Archivo-Light.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <main className={styles.main}>
        <section className="first">
          <ColombiaMap speed={5} />
          <FirstBird />
          <TextBack speed={0} />
          <FirstText speed={-2} />
        </section>
        <section className="second">
          <ListaNomi data={data} />
          <MiddleBird />
          <ThirdBird />
          <Edera position="right" />
          <Edera position="left" />
        </section>
        <section className="third">
          <Lastbird />
          <FormAlert />
        </section>

      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
