import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import ColombiaMap from "./components/colombiaMap";
import TextBack from "./components/textBack";
import FirstText from "./components/firstText";
import ListaNomi from "./components/listaNomi";
export default function Home() {

  const [data, setData] = React.useState(null)

  const getData = () => {
    fetch('./data/dati.json'
      , {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        }
      }
    )
      .then(function (response) {
        return response.json()
      })
      .then(function (myJson) {

        setData(myJson)
      });
  }

  React.useEffect(() => {
    getData()
  }, [])


  return (
    <div className={styles.container}>
      <Head>
       
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/ArchivoBlack-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Archivo-Light.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <main className={styles.main}>
        <section className="first">
          <ColombiaMap speed={5} />
          <TextBack speed={0} />
          <FirstText speed={-2} />
        </section>
        <section className="second">
          <ListaNomi data={data} />
        </section>


      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
